---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: zaepho
name: zohobooks
version: 0.2.0
readme: README.md
authors:
  - Kevin Colby (github.com/zaepho)
description: This Ansible collection provides modules to interact with the Zoho Books API, enabling automation of accounting and financial management tasks.
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - linux
  - zoho
repository: https://github.com/zaepho-org/ansible_collection_zohobooks
documentation: https://github.com/zaepho-org/ansible_collection_zohobooks/tree/main/docs
homepage: https://github.com/zaepho-org/ansible_collection_zohobooks
issues: https://github.com/zaepho-org/ansible_collection_zohobooks/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
